### ISSUE TITLE
Trouble with FS

### ISSUE THREAD

**Issue by Akavvi** [Darkempire78/Discord-Tools#3]
Error: Cannot find module './commands/file'
Require stack:
- A:\devbot\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1085:15)
    at Function.Module._load (internal/modules/cjs/loader.js:928:27)
    at Module.require (internal/modules/cjs/loader.js:1145:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (A:\devbot\index.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'A:\\devbot\\index.js' ]
}

`const commandFiles = fs.readdirSync('./commands').filter(file => file.endsWith('.js'));
for (const file of commandFiles) {
	const command = require(`./commands/file`);
	client.commands.set(command.name, command);
}`

Fix `const commandFiles = fs.readdirSync('./commands').filter(file => file.endsWith('.js'));
for (const file of commandFiles) {
	const command = require(`./commands/${file}`);
	client.commands.set(command.name, command);
}`

**Comment by Darkempire78** [comment]
a new JavaScript bot template arrive in the next update

**Comment by Darkempire78** [comment]
new version released!
